### ISSUE TITLE
1issue sys req Github to jama

### ISSUE THREAD

**Issue by AutomationUIUser** [AutomationUIUser/testRepository#1337]
### 1issue sys req Github to jama
**_description edit_**

1. hi
2. gh

![Screenshot 2023-03-16 211543](https://github.com/AutomationUIUser/testRepository/assets/58691782/86a490df-271b-4539-b9a9-392930cd5545)

**Comment by AutomationUIUser** [comment]
comment added from GtiHub

**Comment by AutomationSyncUser** [comment]
<html>
 <head></head>
 <body>
  <p>comment added from jama<br>Re: @JamaJiraProject-SS-4<br></p>
 </body>
</html>
